name: 'salesforce_formula_integration'
version: '1.3.4'
profile: 'salesforce_formula_integration'
config-version: 2
vars:
  salesforce_formula_integration_tests:
    salesforce_schema: salesforce_formula_integrations_tests

seeds:
  salesforce_formula_integration_tests:
    +quote_columns: "{{ true if target.type == 'redshift' else false }}"
    opportunity:
      +columns_types:
        amount: float
        probability: float
    fivetran_formula:
      +column_types:
        view_sql: "{{ 'varchar(256)'  if target.type in ('redshift','postgres') else 'string'}}"

dispatch:
  - macro_namespace: dbt_utils
    search_order: ['spark_utils', 'dbt_utils']
