name: 'dbt_salesforce_formula_utils'
version: '0.9.3'
profile: 'salesforce_formula_integration'
config-version: 2

models:
  dbt_salesforce_formula_utils:
    +materialized: view
    database: LANDING

dispatch:
  - macro_namespace: dbt_utils
    search_order: ['spark_utils', 'dbt_utils']
